name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build codesign
    - name: Test (MachO)
      run: dotnet test Melanzana.MachO.Tests
    - name: Test (CodeSign)
      run: dotnet test Melanzana.CodeSign.Tests
